# ═══════════════════════════════════════════════════════════════════════════
# Nexus — top-level Makefile  (Windows + macOS/Linux)
#
# Each target does exactly one thing. Compose them yourself:
#   make db          start postgres
#   make migrate     apply migrations
#   make api         start oracle with hot-reload
#
# Or use the shortcuts:
#   make dev         db + migrate + api (postgres in Docker)
#   make dev-sqlite  migrate-sqlite + api-sqlite (zero Docker)
# ═══════════════════════════════════════════════════════════════════════════

ORACLE_DIR       := oracle
COMPOSE_FILE     := docker-compose.yml
K8S_DIR          := k8s
ORACLE_IMAGE     := nexus-oracle:local
MINIKUBE_PROFILE := nexus

# ── OS detection ──────────────────────────────────────────────────────────
# GNU Make sets OS=Windows_NT on all Windows versions.
ifeq ($(OS),Windows_NT)
  SHELL       := powershell.exe
  .SHELLFLAGS := -NoProfile -NonInteractive -Command

  # portable aliases
  WHICH        = where
  RM           = Remove-Item -Force -ErrorAction SilentlyContinue
  MKDIR        = New-Item -ItemType Directory -Force
  SET_ENV      = $$env:
  CD           = Set-Location
  TEST_FILE    = Test-Path
  ECHO         = Write-Host
  # cd into ORACLE_DIR before running a command
  IN_ORACLE    = Set-Location $(ORACLE_DIR);
  # set an env var inline: $(call SETENV,VAR,val) cmd
  SETENV       = $$env:$(1) = "$(2)";
else
  SHELL       := /bin/bash
  .SHELLFLAGS := -euo pipefail -c

  WHICH        = which
  RM           = rm -f
  MKDIR        = mkdir -p
  SET_ENV      = export
  CD           = cd
  TEST_FILE    = test -f
  ECHO         = echo
  IN_ORACLE    = cd $(ORACLE_DIR) &&
  SETENV       = $(1)=$(2)
endif

.DEFAULT_GOAL := help

# ── Help ──────────────────────────────────────────────────────────────────
.PHONY: help
help:
ifeq ($(OS),Windows_NT)
	@Write-Host ""
	@Write-Host "  Nexus -- available targets" -ForegroundColor Cyan
	@Write-Host ""
	@Write-Host "  DATABASE"
	@Write-Host "    make db              start postgres container (idempotent)"
	@Write-Host "    make db-stop         stop postgres container"
	@Write-Host "    make db-status       show postgres health"
	@Write-Host "    make db-shell        open psql shell"
	@Write-Host "    make db-clean        stop + wipe postgres volume (destructive)"
	@Write-Host ""
	@Write-Host "  MIGRATIONS"
	@Write-Host "    make migrate                     apply all pending migrations"
	@Write-Host "    make migrate-sqlite              apply migrations against SQLite"
	@Write-Host "    make migrate-new m=""description"" create autogenerated migration"
	@Write-Host "    make migrate-down                roll back one migration"
	@Write-Host "    make migrate-base                roll back all migrations"
	@Write-Host "    make migrate-status              current revision + history"
	@Write-Host ""
	@Write-Host "  API (oracle)"
	@Write-Host "    make api             start oracle hot-reload (reads oracle/.env)"
	@Write-Host "    make api-sqlite      start oracle with SQLite"
	@Write-Host "    make install         uv sync oracle deps"
	@Write-Host "    make shell           python REPL inside oracle venv"
	@Write-Host ""
	@Write-Host "  SHORTCUTS"
	@Write-Host "    make dev             db + migrate + api"
	@Write-Host "    make dev-sqlite      migrate-sqlite + api-sqlite (zero Docker)"
	@Write-Host ""
	@Write-Host "  DOCKER COMPOSE (full stack)"
	@Write-Host "    make up              all services"
	@Write-Host "    make up-oracle       oracle + postgres only"
	@Write-Host "    make down            stop all containers"
	@Write-Host "    make build           rebuild all images"
	@Write-Host "    make logs            tail all logs"
	@Write-Host "    make logs-oracle     tail oracle logs"
	@Write-Host "    make ps              service health status"
	@Write-Host ""
	@Write-Host "  KUBERNETES (minikube)"
	@Write-Host "    make k8s-up          build + deploy to minikube"
	@Write-Host "    make k8s-down        delete nexus resources"
	@Write-Host "    make k8s-status      pod / service status"
	@Write-Host "    make k8s-logs        tail oracle pod logs"
	@Write-Host ""
	@Write-Host "  QUALITY"
	@Write-Host "    make test            run pytest"
	@Write-Host "    make lint            ruff check"
	@Write-Host "    make fmt             ruff format"
	@Write-Host "    make verify          Phase 0+1 verification script"
	@Write-Host ""
else
	@echo ""
	@echo "  Nexus -- available targets"
	@echo ""
	@echo "  DATABASE"
	@echo "    make db              start postgres container (idempotent)"
	@echo "    make db-stop         stop postgres container"
	@echo "    make db-status       show postgres health"
	@echo "    make db-shell        open psql shell"
	@echo "    make db-clean        stop + wipe postgres volume (destructive)"
	@echo ""
	@echo "  MIGRATIONS"
	@echo "    make migrate                    apply all pending migrations"
	@echo "    make migrate-sqlite             apply migrations against SQLite"
	@echo "    make migrate-new m=description  create autogenerated migration"
	@echo "    make migrate-down               roll back one migration"
	@echo "    make migrate-base               roll back all migrations"
	@echo "    make migrate-status             current revision + history"
	@echo ""
	@echo "  API (oracle)"
	@echo "    make api             start oracle hot-reload (reads oracle/.env)"
	@echo "    make api-sqlite      start oracle with SQLite"
	@echo "    make install         uv sync oracle deps"
	@echo "    make shell           python REPL inside oracle venv"
	@echo ""
	@echo "  SHORTCUTS"
	@echo "    make dev             db + migrate + api"
	@echo "    make dev-sqlite      migrate-sqlite + api-sqlite (zero Docker)"
	@echo ""
	@echo "  DOCKER COMPOSE (full stack)"
	@echo "    make up / down / build / logs / logs-oracle / ps"
	@echo ""
	@echo "  KUBERNETES    make k8s-up / k8s-down / k8s-status / k8s-logs"
	@echo ""
	@echo "  QUALITY       make test / lint / fmt / verify"
	@echo ""
endif

# ── Database ──────────────────────────────────────────────────────────────

.PHONY: db
ifeq ($(OS),Windows_NT)
db:
	@$$status = (docker inspect --format "{{.State.Health.Status}}" nexus-postgres 2>&1); if ($$status -eq "healthy") { Write-Host "[nexus] postgres already running and healthy" -ForegroundColor Green } else { Write-Host "[nexus] starting postgres" -ForegroundColor Yellow; docker compose -f $(COMPOSE_FILE) up -d postgres; Write-Host "[nexus] waiting for postgres..."; $$attempts = 0; $$s = ""; while ($$s -ne "healthy" -and $$attempts -lt 60) { Start-Sleep 1; $$attempts++; $$s = (docker inspect --format "{{.State.Health.Status}}" nexus-postgres 2>&1) }; if ($$s -ne "healthy") { Write-Host "[nexus] ERROR: postgres not healthy after 60s" -ForegroundColor Red; exit 1 }; Write-Host "[nexus] postgres ready" -ForegroundColor Green }
else
db:
	@status=$$(docker inspect --format '{{.State.Health.Status}}' nexus-postgres 2>/dev/null || echo "missing"); \
	if [ "$$status" = "healthy" ]; then \
		echo "[nexus] postgres already running and healthy"; \
	else \
		echo "[nexus] starting postgres"; \
		docker compose -f $(COMPOSE_FILE) up -d postgres; \
		echo "[nexus] waiting for postgres..."; \
		attempts=0; s=""; \
		while [ "$$s" != "healthy" ] && [ $$attempts -lt 60 ]; do \
			sleep 1; attempts=$$((attempts+1)); \
			s=$$(docker inspect --format '{{.State.Health.Status}}' nexus-postgres 2>/dev/null || echo ""); \
		done; \
		if [ "$$s" != "healthy" ]; then echo "[nexus] ERROR: postgres not healthy after 60s"; exit 1; fi; \
		echo "[nexus] postgres ready"; \
	fi
endif

.PHONY: db-stop
db-stop:
	docker compose -f $(COMPOSE_FILE) stop postgres

.PHONY: db-status
db-status:
	docker inspect --format "Health: {{.State.Health.Status}}  State: {{.State.Status}}" nexus-postgres

.PHONY: db-shell
db-shell:
	docker exec -it nexus-postgres psql -U nexus -d nexus

.PHONY: db-clean
ifeq ($(OS),Windows_NT)
db-clean:
	@Write-Host "[nexus] removing postgres container + volume (data will be lost)" -ForegroundColor Red
	docker compose -f $(COMPOSE_FILE) down -v --remove-orphans
	docker volume rm nexus_pg_data 2>&1 | Out-Null; $$true
	@Write-Host "[nexus] clean -- run 'make db' to start fresh" -ForegroundColor Green
else
db-clean:
	@echo "[nexus] removing postgres container + volume (data will be lost)"
	docker compose -f $(COMPOSE_FILE) down -v --remove-orphans
	docker volume rm nexus_pg_data 2>/dev/null || true
	@echo "[nexus] clean -- run 'make db' to start fresh"
endif

# ── Migrations ────────────────────────────────────────────────────────────

.PHONY: migrate
ifeq ($(OS),Windows_NT)
migrate: install
	@Write-Host "[nexus] applying migrations -> postgres" -ForegroundColor Yellow
	Set-Location $(ORACLE_DIR); uv run alembic upgrade head
else
migrate: install
	@echo "[nexus] applying migrations -> postgres"
	cd $(ORACLE_DIR) && uv run alembic upgrade head
endif

.PHONY: migrate-sqlite
ifeq ($(OS),Windows_NT)
migrate-sqlite: install
	@Write-Host "[nexus] applying migrations -> SQLite" -ForegroundColor Yellow
	Set-Location $(ORACLE_DIR); $$env:DATABASE_URL = "sqlite+aiosqlite:///./dev.db"; uv run alembic upgrade head
else
migrate-sqlite: install
	@echo "[nexus] applying migrations -> SQLite"
	cd $(ORACLE_DIR) && DATABASE_URL="sqlite+aiosqlite:///./dev.db" uv run alembic upgrade head
endif

.PHONY: migrate-new
ifeq ($(OS),Windows_NT)
migrate-new: install
	@if (-not "$(m)") { Write-Host "[nexus] ERROR: provide m=""describe change""" -ForegroundColor Red; exit 1 }
	@Write-Host "[nexus] generating migration: $(m)" -ForegroundColor Yellow
	Set-Location $(ORACLE_DIR); uv run alembic revision --autogenerate -m "$(m)"
	@Write-Host "[nexus] review oracle/alembic/versions/ before running make migrate" -ForegroundColor Cyan
else
migrate-new: install
	@[ -n "$(m)" ] || (echo "[nexus] ERROR: provide m='describe change'"; exit 1)
	@echo "[nexus] generating migration: $(m)"
	cd $(ORACLE_DIR) && uv run alembic revision --autogenerate -m "$(m)"
	@echo "[nexus] review oracle/alembic/versions/ before running make migrate"
endif

.PHONY: migrate-down
ifeq ($(OS),Windows_NT)
migrate-down: install
	@Write-Host "[nexus] rolling back one migration" -ForegroundColor Yellow
	Set-Location $(ORACLE_DIR); uv run alembic downgrade -1
else
migrate-down: install
	@echo "[nexus] rolling back one migration"
	cd $(ORACLE_DIR) && uv run alembic downgrade -1
endif

.PHONY: migrate-base
ifeq ($(OS),Windows_NT)
migrate-base: install
	@Write-Host "[nexus] rolling back ALL migrations" -ForegroundColor Red
	Set-Location $(ORACLE_DIR); uv run alembic downgrade base
else
migrate-base: install
	@echo "[nexus] rolling back ALL migrations"
	cd $(ORACLE_DIR) && uv run alembic downgrade base
endif

.PHONY: migrate-status
ifeq ($(OS),Windows_NT)
migrate-status: install
	@Write-Host "[nexus] current revision:" -ForegroundColor Cyan
	Set-Location $(ORACLE_DIR); uv run alembic current
	@Write-Host "[nexus] history:" -ForegroundColor Cyan
	Set-Location $(ORACLE_DIR); uv run alembic history --verbose
else
migrate-status: install
	@echo "[nexus] current revision:"
	cd $(ORACLE_DIR) && uv run alembic current
	@echo "[nexus] history:"
	cd $(ORACLE_DIR) && uv run alembic history --verbose
endif

# ── API (oracle server) ───────────────────────────────────────────────────

.PHONY: api
ifeq ($(OS),Windows_NT)
api: install
	@Write-Host "[nexus] oracle starting on http://localhost:8000 (hot-reload)" -ForegroundColor Green
	Set-Location $(ORACLE_DIR); uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app
else
api: install
	@echo "[nexus] oracle starting on http://localhost:8000 (hot-reload)"
	cd $(ORACLE_DIR) && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app
endif

.PHONY: api-sqlite
ifeq ($(OS),Windows_NT)
api-sqlite: install
	@Write-Host "[nexus] oracle starting with SQLite on http://localhost:8000" -ForegroundColor Green
	Set-Location $(ORACLE_DIR); $$env:DATABASE_URL = "sqlite+aiosqlite:///./dev.db"; uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app
else
api-sqlite: install
	@echo "[nexus] oracle starting with SQLite on http://localhost:8000"
	cd $(ORACLE_DIR) && DATABASE_URL="sqlite+aiosqlite:///./dev.db" uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app
endif

.PHONY: install
ifeq ($(OS),Windows_NT)
install:
	Set-Location $(ORACLE_DIR); uv sync --quiet
else
install:
	cd $(ORACLE_DIR) && uv sync --quiet
endif

.PHONY: shell
ifeq ($(OS),Windows_NT)
shell: install
	Set-Location $(ORACLE_DIR); uv run python
else
shell: install
	cd $(ORACLE_DIR) && uv run python
endif

# ── Shortcuts ─────────────────────────────────────────────────────────────

.PHONY: dev
dev: db migrate api

.PHONY: dev-sqlite
dev-sqlite: migrate-sqlite api-sqlite

# ── Docker Compose ────────────────────────────────────────────────────────

.PHONY: up
up:
	docker compose -f $(COMPOSE_FILE) up -d

.PHONY: up-oracle
up-oracle:
	docker compose -f $(COMPOSE_FILE) up -d oracle postgres

.PHONY: down
down:
	docker compose -f $(COMPOSE_FILE) down

.PHONY: build
build:
	docker compose -f $(COMPOSE_FILE) build

.PHONY: logs
logs:
	docker compose -f $(COMPOSE_FILE) logs -f

.PHONY: logs-oracle
logs-oracle:
	docker compose -f $(COMPOSE_FILE) logs -f oracle

.PHONY: ps
ps:
	docker compose -f $(COMPOSE_FILE) ps

# ── Kubernetes (minikube) ─────────────────────────────────────────────────

.PHONY: k8s-up
ifeq ($(OS),Windows_NT)
k8s-up:
	@Write-Host "[nexus] building oracle image into minikube" -ForegroundColor Yellow
	& minikube -p $(MINIKUBE_PROFILE) docker-env --shell powershell | Invoke-Expression
	docker build -t $(ORACLE_IMAGE) $(ORACLE_DIR)
	kubectl apply -f $(K8S_DIR)/
	@Write-Host "[nexus] deployed -- run 'make k8s-status'" -ForegroundColor Green
else
k8s-up:
	@echo "[nexus] building oracle image into minikube"
	eval $$(minikube -p $(MINIKUBE_PROFILE) docker-env)
	docker build -t $(ORACLE_IMAGE) $(ORACLE_DIR)
	kubectl apply -f $(K8S_DIR)/
	@echo "[nexus] deployed -- run 'make k8s-status'"
endif

.PHONY: k8s-down
k8s-down:
	kubectl delete -f $(K8S_DIR)/ --ignore-not-found

.PHONY: k8s-status
k8s-status:
	kubectl get pods,services,deployments -l app=nexus

.PHONY: k8s-logs
k8s-logs:
	kubectl logs -l app=nexus-oracle -f --tail=100

# ── Quality ───────────────────────────────────────────────────────────────

.PHONY: test
ifeq ($(OS),Windows_NT)
test: install
	Set-Location $(ORACLE_DIR); uv sync --extra dev --quiet; .\.venv\Scripts\python.exe -m pytest
else
test: install
	cd $(ORACLE_DIR) && uv sync --extra dev --quiet && .venv/bin/python -m pytest
endif

.PHONY: lint
ifeq ($(OS),Windows_NT)
lint: install
	Set-Location $(ORACLE_DIR); uv run ruff check app/
else
lint: install
	cd $(ORACLE_DIR) && uv run ruff check app/
endif

.PHONY: fmt
ifeq ($(OS),Windows_NT)
fmt: install
	Set-Location $(ORACLE_DIR); uv run ruff format app/
else
fmt: install
	cd $(ORACLE_DIR) && uv run ruff format app/
endif

.PHONY: verify
ifeq ($(OS),Windows_NT)
verify: install
	@Write-Host "[nexus] running Phase 0+1 verification" -ForegroundColor Yellow
	Set-Location $(ORACLE_DIR); $$env:DATABASE_URL = "sqlite+aiosqlite:///./verify_test.db"; uv run alembic upgrade head
	Set-Location $(ORACLE_DIR); $$env:DATABASE_URL = "sqlite+aiosqlite:///./verify_test.db"; uv run python verify_phase01.py
	if (Test-Path "$(ORACLE_DIR)/verify_test.db") { Remove-Item "$(ORACLE_DIR)/verify_test.db" }
else
verify: install
	@echo "[nexus] running Phase 0+1 verification"
	cd $(ORACLE_DIR) && DATABASE_URL="sqlite+aiosqlite:///./verify_test.db" uv run alembic upgrade head
	cd $(ORACLE_DIR) && DATABASE_URL="sqlite+aiosqlite:///./verify_test.db" uv run python verify_phase01.py
	@rm -f $(ORACLE_DIR)/verify_test.db
endif
